<#
.SYNOPSIS
  Apply a Potter flavor as your Windows theme. AUTO-GENERATED by Quills.
.DESCRIPTION
  Flips the app/system light-dark mode and accent color in the registry (accent
  swatch, title bars, taskbar, Start), then broadcasts a refresh. Windows 10/11
  ignores a .theme file's color/mode keys for the live theme, so this script
  sets the registry directly instead of launching the .theme.
.EXAMPLE
  ./Apply-Potter.ps1                 # Quill (default dark)
  ./Apply-Potter.ps1 -Flavor parchment
  ./Apply-Potter.ps1 -Flavor ink
.NOTES
  Accent/mode apply immediately; Start menu and taskbar refresh on next sign-in.
#>
param(
  [ValidateSet('parchment', 'quill', 'ink')]
  [string]$Flavor = 'quill'
)

$ErrorActionPreference = 'Stop'

$flavors = @{
  'parchment' = @{ Name = 'Potter Parchment'; Accent = 'd77250'; Dark = $false }
  'quill' = @{ Name = 'Potter Quill'; Accent = 'e08a6a'; Dark = $true }
  'ink' = @{ Name = 'Potter Ink'; Accent = 'e28c6c'; Dark = $true }
}

$f = $flavors[$Flavor]

$rr = [Convert]::ToInt32($f.Accent.Substring(0, 2), 16)
$gg = [Convert]::ToInt32($f.Accent.Substring(2, 2), 16)
$bb = [Convert]::ToInt32($f.Accent.Substring(4, 2), 16)

# Windows 10/11 drives the live accent + light/dark mode from the registry, NOT
# from a .theme file's ColorizationColor/SystemMode (those are ignored on modern
# builds). So this script writes the registry directly and broadcasts a refresh
# rather than launching the .theme. The .theme files are kept only as an optional
# Settings-gallery entry.

# 1. Light/dark mode.
$personalize = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize'
$lightValue = if ($f.Dark) { 0 } else { 1 }
New-Item -Path $personalize -Force | Out-Null
Set-ItemProperty $personalize -Name 'AppsUseLightTheme'    -Value $lightValue -Type DWord
Set-ItemProperty $personalize -Name 'SystemUsesLightTheme' -Value $lightValue -Type DWord
Set-ItemProperty $personalize -Name 'ColorPrevalence'      -Value 1 -Type DWord

# 3. Accent color. DWM stores accent as 0xAABBGGRR (ABGR); colorization wants
#    0xAARRGGBB (ARGB). Reorder from the RRGGBB hex.
$abgr = [int64](0xFF000000 -bor ($bb -shl 16) -bor ($gg -shl 8) -bor $rr)
$argb = [int64](0xFF000000 -bor ($rr -shl 16) -bor ($gg -shl 8) -bor $bb)

$dwm = 'HKCU:\Software\Microsoft\Windows\DWM'
New-Item -Path $dwm -Force | Out-Null
Set-ItemProperty $dwm -Name 'AccentColor'              -Value $abgr -Type DWord
Set-ItemProperty $dwm -Name 'ColorizationColor'        -Value $argb -Type DWord
Set-ItemProperty $dwm -Name 'ColorizationAfterglow'    -Value $argb -Type DWord
Set-ItemProperty $dwm -Name 'EnableWindowColorization' -Value 1     -Type DWord

# 4. Accent shade ramp. AccentPalette is 8 entries x (R G B 00), light->dark;
#    index 3 is the base accent, index 7 is Windows' fixed contrast constant.
function Blend([int]$c, [double]$t) {
  # t > 0 tints toward white, t < 0 shades toward black.
  if ($t -ge 0) { [byte][math]::Round($c + (255 - $c) * $t) }
  else { [byte][math]::Round($c * (1 + $t)) }
}
$ramp = @(0.62, 0.38, 0.16, 0.0, -0.16, -0.42, -0.66)
$bytes = New-Object System.Collections.Generic.List[byte]
foreach ($t in $ramp) {
  $bytes.Add((Blend $rr $t)); $bytes.Add((Blend $gg $t)); $bytes.Add((Blend $bb $t)); $bytes.Add(0)
}
$bytes.AddRange([byte[]](0xF7, 0x63, 0x0C, 0x00))   # fixed trailing constant

$accent = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Accent'
New-Item -Path $accent -Force | Out-Null
Set-ItemProperty $accent -Name 'AccentColorMenu' -Value $abgr -Type DWord
Set-ItemProperty $accent -Name 'StartColorMenu'  -Value $abgr -Type DWord
Set-ItemProperty $accent -Name 'AccentPalette'   -Value $bytes.ToArray() -Type Binary

# 5. Tell the shell to re-read the accent without a sign-out.
if (-not ('PotterNative' -as [type])) {
  Add-Type -Name PotterNative -Namespace Win32 -MemberDefinition @'
[System.Runtime.InteropServices.DllImport("user32.dll", SetLastError = true, CharSet = System.Runtime.InteropServices.CharSet.Auto)]
public static extern System.IntPtr SendMessageTimeout(System.IntPtr hWnd, uint Msg, System.UIntPtr wParam, string lParam, uint flags, uint timeout, out System.UIntPtr result);
'@
}
$res = [System.UIntPtr]::Zero
[void][Win32.PotterNative]::SendMessageTimeout([System.IntPtr]0xffff, 0x1A, [System.UIntPtr]::Zero, 'ImmersiveColorSet', 2, 300, [ref]$res)

Write-Host "Applied $($f.Name) - accent #$($f.Accent), $(if ($f.Dark) {'dark'} else {'light'}) mode." -ForegroundColor Green
Write-Host 'Title bars/taskbar/Start update now; a few apps refresh on next sign-in.'
