-- Potter Parchment — WezTerm. AUTO-GENERATED by Quills.
-- local potter = require("potter-parchment")
-- config.colors = potter
return {
  foreground = "#141413",
  background = "#faf9f5",
  cursor_bg = "#d77250",
  cursor_fg = "#faf9f5",
  cursor_border = "#d77250",
  selection_bg = "#a89e8c",
  selection_fg = "#faf9f5",
  scrollbar_thumb = "#d6cab4",
  split = "#e3dacc",
  ansi = {
    "#e3dacc", "#b02619", "#788c5d", "#bd8324", "#4a6da0", "#9a6aa0", "#4f8a78", "#6b6357", 
  },
  brights = {
    "#d6cab4", "#b02619", "#788c5d", "#bd8324", "#4a6da0", "#9a6aa0", "#4f8a78", "#897f6d", 
  },
  tab_bar = {
    background = "#f2eee4",
    active_tab = { bg_color = "#d77250", fg_color = "#faf9f5" },
    inactive_tab = { bg_color = "#f2eee4", fg_color = "#897f6d" },
  },
}
