-- Potter Quill — WezTerm. AUTO-GENERATED by Quills.
-- local potter = require("potter-quill")
-- config.colors = potter
return {
  foreground = "#efe9df",
  background = "#1c1812",
  cursor_bg = "#e08a6a",
  cursor_fg = "#1c1812",
  cursor_border = "#e08a6a",
  selection_bg = "#8f7f64",
  selection_fg = "#1c1812",
  scrollbar_thumb = "#453829",
  split = "#362c20",
  ansi = {
    "#362c20", "#d77b6e", "#9cb07d", "#e0b25a", "#8aa6c8", "#c2a3c8", "#84b3a4", "#c8bca4", 
  },
  brights = {
    "#453829", "#d77b6e", "#9cb07d", "#e0b25a", "#8aa6c8", "#c2a3c8", "#84b3a4", "#a99e8d", 
  },
  tab_bar = {
    background = "#17140f",
    active_tab = { bg_color = "#e08a6a", fg_color = "#1c1812" },
    inactive_tab = { bg_color = "#17140f", fg_color = "#a99e8d" },
  },
}
