-- Potter Ink — WezTerm. AUTO-GENERATED by Quills.
-- local potter = require("potter-ink")
-- config.colors = potter
return {
  foreground = "#ece6da",
  background = "#14110c",
  cursor_bg = "#e28c6c",
  cursor_fg = "#14110c",
  cursor_border = "#e28c6c",
  selection_bg = "#88795e",
  selection_fg = "#14110c",
  scrollbar_thumb = "#3b3122",
  split = "#2e261b",
  ansi = {
    "#2e261b", "#d87d70", "#9eb27f", "#e2b45c", "#8ca8ca", "#c4a5ca", "#86b5a6", "#c3b79f", 
  },
  brights = {
    "#3b3122", "#d87d70", "#9eb27f", "#e2b45c", "#8ca8ca", "#c4a5ca", "#86b5a6", "#a39884", 
  },
  tab_bar = {
    background = "#0f0c08",
    active_tab = { bg_color = "#e28c6c", fg_color = "#14110c" },
    inactive_tab = { bg_color = "#0f0c08", fg_color = "#a39884" },
  },
}
