/**
 * Builds the canonical palette.json (source-of-truth artifact) plus programmatic
 * bindings under palette/dist/, derived entirely from palette/src/colors.ts.
 *
 * Run: `npm run build-palette`  (node palette/src/build.ts)
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { hexToRgb, hexToHsl } from "../../lib/color.ts";
import {
  FLAVORS,
  ACCENTS,
  COLOR_ORDER,
  ANSI_MAP,
  type ColorName,
  type FlavorName,
} from "./colors.ts";

const here = dirname(fileURLToPath(import.meta.url));
const paletteDir = resolve(here, "..");
const distDir = resolve(paletteDir, "dist");

const ACCENT_SET = new Set<string>(ACCENTS);

interface ColorEntry {
  hex: string;
  rgb: { r: number; g: number; b: number };
  hsl: { h: number; s: number; l: number };
  accent: boolean;
}

function colorEntry(name: ColorName, hex: string): ColorEntry {
  return {
    hex,
    rgb: hexToRgb(hex),
    hsl: hexToHsl(hex),
    accent: ACCENT_SET.has(name),
  };
}

function ansiEntry(hex: string, code: number) {
  return { hex, rgb: hexToRgb(hex), hsl: hexToHsl(hex), code };
}

function buildPalette() {
  const out: Record<string, unknown> = {
    $schema: "https://potter-theme.dev/palette-schema.json",
    version: "0.1.0",
  };

  for (const fname of Object.keys(FLAVORS) as FlavorName[]) {
    const flavor = FLAVORS[fname];
    const colors: Record<string, ColorEntry> = {};
    for (const cname of COLOR_ORDER) {
      colors[cname] = colorEntry(cname, flavor.colors[cname]);
    }

    const ansi: Record<string, unknown> = {};
    for (const a of ANSI_MAP) {
      ansi[a.name] = {
        name: a.name[0].toUpperCase() + a.name.slice(1),
        order: a.code,
        normal: ansiEntry(flavor.colors[a.normal], a.code),
        bright: ansiEntry(flavor.colors[a.bright], a.code + 8),
      };
    }

    out[fname] = {
      name: flavor.name,
      dark: flavor.dark,
      order: flavor.order,
      colors,
      ansi,
    };
  }
  return out;
}

const palette = buildPalette();

mkdirSync(distDir, { recursive: true });

const json = JSON.stringify(palette, null, 2) + "\n";
writeFileSync(resolve(paletteDir, "palette.json"), json);
writeFileSync(resolve(distDir, "palette.json"), json);

// --- Typed JS binding (ESM) consumers can `import { flavors } from "@potternu/palette"` ---
const jsBinding = `// AUTO-GENERATED by palette/src/build.ts — do not edit.
import palette from "./palette.json" with { type: "json" };

export default palette;
export const flavors = ["parchment", "quill", "ink"];
export const accents = ${JSON.stringify([...ACCENTS])};
export const parchment = palette.parchment;
export const quill = palette.quill;
export const ink = palette.ink;

/** Look up a single color's hex. e.g. color("quill", "peach") */
export function color(flavor, name) {
  return palette[flavor].colors[name].hex;
}
`;
writeFileSync(resolve(distDir, "index.js"), jsBinding);

// --- Type declarations ---
const colorUnion = COLOR_ORDER.map((c) => `"${c}"`).join(" | ");
const dts = `// AUTO-GENERATED by palette/src/build.ts — do not edit.
export type FlavorName = "parchment" | "quill" | "ink";
export type ColorName = ${colorUnion};
export interface ColorEntry {
  hex: string;
  rgb: { r: number; g: number; b: number };
  hsl: { h: number; s: number; l: number };
  accent: boolean;
}
export interface AnsiVariant { hex: string; rgb: { r: number; g: number; b: number }; hsl: { h: number; s: number; l: number }; code: number; }
export interface AnsiEntry { name: string; order: number; normal: AnsiVariant; bright: AnsiVariant; }
export interface Flavor {
  name: string;
  dark: boolean;
  order: number;
  colors: Record<ColorName, ColorEntry>;
  ansi: Record<string, AnsiEntry>;
}
export interface Palette { version: string; parchment: Flavor; quill: Flavor; ink: Flavor; }
declare const palette: Palette;
export default palette;
export const flavors: FlavorName[];
export const accents: ColorName[];
export const parchment: Flavor;
export const quill: Flavor;
export const ink: Flavor;
export function color(flavor: FlavorName, name: ColorName): string;
`;
writeFileSync(resolve(distDir, "index.d.ts"), dts);

const count = COLOR_ORDER.length;
console.log(
  `✓ palette built: 3 flavors × ${count} colors → palette.json + dist/{index.js,index.d.ts,palette.json}`,
);
